apiVersion: apps/v1
kind: Deployment
metadata:
  name:pers
spec:
  replicas: 1
  selector:
    matchLabels:
      app:pers
  template:
    metadata:
      labels:
        app: pers
    spec:
      containers:
      - image: okteto.dev/pers:latest
        name: pers
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "42acaf55-a82c-4a6d-98ce-c74fe3bdfbaa"
        - name: Vless_Path
          value: "/vl33bbs5"
        - name: Vmess_UUID
          value: "42acaf55-a82c-4a6d-98ce-c74fe3bdfbaa"
        - name: Vmess_Path
          value: "/vm66vv3346"
        - name: Share_Path
          value: "/v2link"
